// 50 cards
let narutoDeck = {
    cards: [
        {
            id: 0,
            title: 'Asuma Sarutobi',
            pictureDir: '/images/naruto/asuma.png',
            chosen: false,
        },
        {
            id: 1,
            title: 'Deidara',
            pictureDir: '/images/naruto/deidara.jpeg',
            chosen: false,
        },
        {
            id: 2,
            title: 'Gaara',
            pictureDir: '/images/naruto/gaara.jpeg',
            chosen: false,
        },
        {
            id: 3,
            title: 'Hidan',
            pictureDir: '/images/naruto/hidan.png',
            chosen: false,
        },
        {
            id: 4,
            title: 'Hinata Hyuga',
            pictureDir: '/images/naruto/hinata.jpeg',
            chosen: false,
        },
        {
            id: 5,
            title: 'Ino Yamanaka',
            pictureDir: '/images/naruto/ino.jpeg',
            chosen: false,
        },
        {
            id: 6,
            title: 'Itachi Uchiha',
            pictureDir: '/images/naruto/itachi.jpeg',
            chosen: false,
        },
        {
            id: 7,
            title: 'Jiraiya',
            pictureDir: '/images/naruto/jiraiya.jpeg',
            chosen: false,
        },
        {
            id: 8,
            title: 'Kakashi Hatake',
            pictureDir: '/images/naruto/kakashi.jpeg',
            chosen: false,
        },
        {
            id: 9,
            title: 'Kakuzu',
            pictureDir: '/images/naruto/kakuzu.jpeg',
            chosen: false,
        },
        {
            id: 10,
            title: 'Madara Uchiha',
            pictureDir: '/images/naruto/madara.jpeg',
            chosen: false,
        },
        {
            id: 11,
            title: 'Minato Namikaze',
            pictureDir: '/images/naruto/minato.jpeg',
            chosen: false,
        },
        {
            id: 12,
            title: 'Nagato',
            pictureDir: '/images/naruto/nagato.jpeg',
            chosen: false,
        },
        {
            id: 13,
            title: 'Naruto Uzumaki',
            pictureDir: '/images/naruto/naruto.jpeg',
            chosen: false,
        },
        {
            id: 14,
            title: 'Neji Hyuga',
            pictureDir: '/images/naruto/neji.jpeg',
            chosen: false,
        },
        {
            id: 15,
            title: 'Obito Uchiha',
            pictureDir: '/images/naruto/obito.jpeg',
            chosen: false,
        },
        {
            id: 16,
            title: 'Orochimaru',
            pictureDir: '/images/naruto/orochimaru.jpeg',
            chosen: false,
        },
        {
            id: 17,
            title: 'Rock Lee',
            pictureDir: '/images/naruto/rock-lee.webp',
            chosen: false,
        },
        {
            id: 18,
            title: 'Sakura Haruno',
            pictureDir: '/images/naruto/sakura.jpeg',
            chosen: false,
        },
        {
            id: 19,
            title: 'Sasori',
            pictureDir: '/images/naruto/sasori.jpeg',
            chosen: false,
        },
        {
            id: 20,
            title: 'Shikamaru Nara',
            pictureDir: '/images/naruto/shikamaru.jpeg',
            chosen: false,
        },
        {
            id: 21,
            title: 'Temari',
            pictureDir: '/images/naruto/temari.jpeg',
            chosen: false,
        },
        {
            id: 22,
            title: 'Sasuke Uchiha',
            pictureDir: '/images/naruto/sasuke.webp',
            chosen: false,
        },
        {
            id: 23,
            title: 'Tsunade',
            pictureDir: '/images/naruto/tsunade.jpeg',
            chosen: false,
        },
        {
            id: 24,
            title: 'Danzo Shimura',
            pictureDir: '/images/naruto/danzo.jpeg',
            chosen: false,
        },
        {
            id: 25,
            title: 'Sai',
            pictureDir: '/images/naruto/sai.webp',
            chosen: false,
        },
        {
            id: 26,
            title: 'Kabuto Yakushi',
            pictureDir: '/images/naruto/kabuto.jpeg',
            chosen: false,
        },
        {
            id: 27,
            title: 'Killer Bee',
            pictureDir: '/images/naruto/bee.png',
            chosen: false,
        },
        {
            id: 28,
            title: 'Kushina Uzumaki',
            pictureDir: '/images/naruto/kushina.jpeg',
            chosen: false,
        },
        {
            id: 29,
            title: 'Yamato',
            pictureDir: '/images/naruto/yamato.jpeg',
            chosen: false,
        },
        {
            id: 30,
            title: 'Karin',
            pictureDir: '/images/naruto/karin.webp',
            chosen: false,
        },
        {
            id: 31,
            title: 'Konan',
            pictureDir: '/images/naruto/konan.webp',
            chosen: false,
        },
        {
            id: 32,
            title: 'Tenten',
            pictureDir: '/images/naruto/tenten.jpeg',
            chosen: false,
        },
        {
            id: 33,
            title: 'Shizune',
            pictureDir: '/images/naruto/shizune.webp',
            chosen: false,
        },
        {
            id: 34,
            title: 'Might Guy',
            pictureDir: '/images/naruto/guy.jpeg',
            chosen: false,
        },
        {
            id: 35,
            title: 'Konohamaru Sarutobi',
            pictureDir: '/images/naruto/konohamaru.jpeg',
            chosen: false,
        },
        {
            id: 36,
            title: 'Kankuro',
            pictureDir: '/images/naruto/kankuro.jpeg',
            chosen: false,
        },
        {
            id: 37,
            title: 'Hiruzen Sarutobi',
            pictureDir: '/images/naruto/hiruzen.jpeg',
            chosen: false,
        },
        {
            id: 38,
            title: 'Tobirama Senju',
            pictureDir: '/images/naruto/tobirama.jpeg',
            chosen: false,
        },
        {
            id: 39,
            title: 'Hashirama Senju',
            pictureDir: '/images/naruto/hashirama.png',
            chosen: false,
        },
        {
            id: 40,
            title: 'Kurenai Yuhi',
            pictureDir: '/images/naruto/kurenai.jpeg',
            chosen: false,
        },
        {
            id: 41,
            title: 'Choji Akimichi',
            pictureDir: '/images/naruto/choji.jpeg',
            chosen: false,
        },
        {
            id: 42,
            title: 'Shino Aburame',
            pictureDir: '/images/naruto/shino.jpeg',
            chosen: false,
        },
        {
            id: 43,
            title: 'Kisame Hoshigaki',
            pictureDir: '/images/naruto/kisame.webp',
            chosen: false,
        },
        {
            id: 44,
            title: 'Zetsu',
            pictureDir: '/images/naruto/zetsu.webp',
            chosen: false,
        },
        {
            id: 45,
            title: 'Iruka Umino',
            pictureDir: '/images/naruto/iruka.png',
            chosen: false,
        },
        {
            id: 46,
            title: 'Kiba Inuzuka',
            pictureDir: '/images/naruto/kiba.jpeg',
            chosen: false,
        },
        {
            id: 47,
            title: 'Baki',
            pictureDir: '/images/naruto/baki.jpeg',
            chosen: false,
        },
        {
            id: 48,
            title: 'Yahiko',
            pictureDir: '/images/naruto/yahiko.jpeg',
            chosen: false,
        },
        {
            id: 49,
            title: 'Zabuza Momochi',
            pictureDir: '/images/naruto/zabuza.png',
            chosen: false,
        },
    ]
}

export default narutoDeck;